using System.Text;

namespace Tamp.AdjacentContainer.Provisioning;

/// <summary>
/// Generates the <c>docker-compose.yml</c> body for a configured sidecar set.
/// Deterministic output: same inputs always produce byte-identical YAML so
/// adopters can diff the file in CI.
/// </summary>
internal static class ComposeWriter
{
    public static string Write(
        string projectName,
        PostgresSidecar? pg,
        AzuriteSidecar? az,
        ServiceBusEmulatorSidecar? sb)
    {
        var yaml = new StringBuilder();
        yaml.Append("# Generated by Tamp.AdjacentContainer.Provisioning. Do not hand-edit.\n");
        yaml.Append($"# Project: {projectName}\n");
        yaml.Append("\n");
        yaml.Append("name: ").Append(projectName).Append('\n');
        yaml.Append("services:\n");

        if (pg is not null) WritePostgres(yaml, pg);
        if (az is not null) WriteAzurite(yaml, az);
        if (sb is not null) WriteServiceBus(yaml, sb);

        yaml.Append("\n");
        yaml.Append("volumes:\n");
        if (pg is not null) yaml.Append($"  {pg.ServiceName}-data: {{}}\n");
        if (az is not null) yaml.Append($"  {az.ServiceName}-data: {{}}\n");

        return yaml.ToString();
    }

    private static void WritePostgres(StringBuilder yaml, PostgresSidecar pg)
    {
        yaml.Append($"  {pg.ServiceName}:\n");
        yaml.Append($"    image: {pg.Image}\n");
        yaml.Append( "    restart: unless-stopped\n");
        yaml.Append( "    environment:\n");
        yaml.Append($"      POSTGRES_DB: {pg.Database}\n");
        yaml.Append($"      POSTGRES_USER: {pg.Username}\n");
        yaml.Append($"      POSTGRES_PASSWORD: {pg.Password}\n");
        yaml.Append( "    ports:\n");
        yaml.Append($"      - \"{pg.HostPort}:5432\"\n");
        yaml.Append( "    volumes:\n");
        yaml.Append($"      - {pg.ServiceName}-data:/var/lib/postgresql/data\n");
        yaml.Append( "    healthcheck:\n");
        yaml.Append($"      test: [\"CMD-SHELL\", \"pg_isready -U {pg.Username} -d {pg.Database}\"]\n");
        yaml.Append( "      interval: 2s\n");
        yaml.Append( "      timeout: 5s\n");
        yaml.Append( "      retries: 20\n");
    }

    private static void WriteAzurite(StringBuilder yaml, AzuriteSidecar az)
    {
        yaml.Append($"  {az.ServiceName}:\n");
        yaml.Append($"    image: {az.Image}\n");
        yaml.Append( "    restart: unless-stopped\n");
        yaml.Append( "    command: \"azurite --loose --skipApiVersionCheck --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data\"\n");
        yaml.Append( "    ports:\n");
        yaml.Append($"      - \"{az.BlobPort}:10000\"\n");
        yaml.Append($"      - \"{az.QueuePort}:10001\"\n");
        yaml.Append($"      - \"{az.TablePort}:10002\"\n");
        yaml.Append( "    volumes:\n");
        yaml.Append($"      - {az.ServiceName}-data:/data\n");
        yaml.Append( "    healthcheck:\n");
        yaml.Append( "      test: [\"CMD-SHELL\", \"nc -z localhost 10000 || exit 1\"]\n");
        yaml.Append( "      interval: 2s\n");
        yaml.Append( "      timeout: 5s\n");
        yaml.Append( "      retries: 20\n");
    }

    private static void WriteServiceBus(StringBuilder yaml, ServiceBusEmulatorSidecar sb)
    {
        yaml.Append($"  {sb.ServiceName}:\n");
        yaml.Append($"    image: {sb.Image}\n");
        yaml.Append( "    restart: unless-stopped\n");
        yaml.Append( "    environment:\n");
        yaml.Append($"      ACCEPT_EULA: {sb.EmulatorAcceptEula}\n");
        yaml.Append( "      SQL_SERVER: ${SQL_SERVER:-mssql}\n");
        yaml.Append( "      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-emulator-pwd-Aa1!}\n");
        yaml.Append( "    ports:\n");
        yaml.Append($"      - \"{sb.HostPort}:5672\"\n");
        if (!string.IsNullOrEmpty(sb.ConfigJsonPath))
        {
            yaml.Append( "    volumes:\n");
            yaml.Append($"      - {sb.ConfigJsonPath}:/ServiceBus_Emulator/ConfigFiles/Config.json:ro\n");
        }
        yaml.Append( "    healthcheck:\n");
        yaml.Append( "      test: [\"CMD-SHELL\", \"nc -z localhost 5672 || exit 1\"]\n");
        yaml.Append( "      interval: 2s\n");
        yaml.Append( "      timeout: 5s\n");
        yaml.Append( "      retries: 30\n");
    }
}

/// <summary>Builds the env-var dictionary that <c>Tamp.AdjacentContainer</c>'s fixture-side <c>AcquireAsync</c> reads.</summary>
internal static class EnvWriter
{
    public const string PostgresEnvVarKey = "TAMP_PG_CONNECTION";
    public const string AzuriteEnvVarKey = "TAMP_AZURITE_CONNECTION";
    public const string ServiceBusEnvVarKey = "TAMP_SBUS_CONNECTION";

    public static IReadOnlyDictionary<string, string> Build(
        PostgresSidecar? pg,
        AzuriteSidecar? az,
        ServiceBusEmulatorSidecar? sb)
    {
        var env = new Dictionary<string, string>(StringComparer.Ordinal);
        if (pg is not null) env[PostgresEnvVarKey] = pg.ConnectionString();
        if (az is not null) env[AzuriteEnvVarKey] = az.ConnectionString();
        if (sb is not null) env[ServiceBusEnvVarKey] = sb.ConnectionString();
        return env;
    }
}
